"""Grounded answer generation via an LLM.

The answer is generated by an LLM using a strict grounding prompt: it must use
only the retrieved evidence, refuse if the evidence does not cover the question,
stay patient-friendly, and avoid personal diagnosis. The provider is any
OpenAI-compatible API (OpenAI, Groq, OpenRouter). The prompt template is logged
for research.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List

from .config import settings
from .vectorstore import RetrievedChunk

REFUSAL_MESSAGE = (
    "I'm sorry, but I don't have enough reliable information in my current "
    "knowledge base to answer that safely. I can only answer using the trusted "
    "health documents I've been given, and they don't appear to cover your "
    "question. Please ask your doctor, nurse, or pharmacist, who can give you "
    "advice based on your personal situation."
)

PROMPT_TEMPLATE = """You are a careful patient-education assistant for people with heart failure \
(HFpEF) and related cardio-kidney-metabolic conditions.

Rules:
- Answer ONLY using the evidence passages provided below. Do not use outside knowledge.
- If the evidence does not contain the answer, say you don't have enough information.
- Write in plain, warm, patient-friendly language at roughly a grade 7 reading level.
- Cite sources inline using the exact tags from the evidence, e.g. [doc_hfpef_treatments/chunk_0], \
when stating a fact from that passage.
- Do NOT give a personal diagnosis or tell the patient to start/stop a specific medicine; \
encourage them to discuss specifics with their healthcare team.
- End with a one-sentence reminder that this is general information, not personal medical advice.

Question:
{question}

Evidence passages (each tagged with its document_id / chunk_id):
{evidence_block}

Patient-friendly answer (grounded only in the evidence above):"""

PROMPT_SUMMARY = (
    "Strict grounding prompt: answer only from supplied evidence, inline "
    "[doc/chunk] citations, refuse if uncovered, patient-friendly tone, disclaimer."
)


@dataclass
class GenerationResult:
    answer: str
    model_name: str
    prompt_summary: str = PROMPT_SUMMARY
    prompt_template: str = PROMPT_TEMPLATE
    metadata: dict = field(default_factory=dict)


def _format_evidence_block(results: List[RetrievedChunk]) -> str:
    return "\n\n".join(
        f"[{r.chunk.document_id} / {r.chunk.chunk_id} | score={r.similarity_score:.3f}]"
        f"\n{r.chunk.text}"
        for r in results
    )


def generate_answer(question: str, results: List[RetrievedChunk]) -> GenerationResult:
    """Generate a grounded, patient-friendly answer with the configured LLM."""
    if not settings.llm_api_key:
        raise RuntimeError(
            "No LLM API key configured. Set GROQ_API_KEY / OPENAI_API_KEY / "
            "OPENROUTER_API_KEY (see .env.example)."
        )

    from openai import OpenAI

    prompt = PROMPT_TEMPLATE.format(
        question=question, evidence_block=_format_evidence_block(results)
    )
    client = OpenAI(api_key=settings.llm_api_key, base_url=settings.llm_base_url)
    completion = client.chat.completions.create(
        model=settings.llm_model_name,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.2,
    )
    answer = (completion.choices[0].message.content or "").strip()
    return GenerationResult(
        answer=answer, model_name=f"{settings.llm_provider}:{settings.llm_model_name}"
    )
